---
driver:
  name: ec2
  require_chef_omnibus: 12.14.60
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
- name: ubuntu-14.04
  driver_config:
    tags:
      Name: apache-storm-default-ubuntu-1404
      Env: public

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[zookeeper]
  - role[zookeeper]
  - recipe[apache_storm::supervisor]
  - recipe[apache_storm::nimbus]
  driver_config:
    network:
    - - private_network
      - ip: 192.168.33.10
  attributes:
    exhibitor:
      opts:
        configtype: file
